dist: trusty

services:
  - mongodb

language: node_js
node_js:
- "node"

before_install:
  - npm install

before_script:
  - cd services/backend/
  - npm install

script:
  - npm run build
  - npm run lint
  - npm run test:cov
    