dist: trusty

services:
  - mongodb

matrix:
  include:
  - language: node_js
  node_js:
  - "node"

  env:
    - CXX=g++-6
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-6

  cache: npm

  before_script:
    - cd services/backend/
    - npm install

  script:
    - npm run build
    - npm run lint
    - npm run test:ci
    