dist: trusty

services:
  - mongodb

matrix:
  include:
  - language: node_js
    node_js:
      - "10"

    env:
      - CXX=g++-6
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6

    cache: npm

    before_install:
      - cd services/backend/
      - npm install -g greenkeeper-lockfile
      
    install:  
      - npm install

    before_script: greenkeeper-lockfile-update
    after_script: greenkeeper-lockfile-upload

    script:
      - npm run build
      - npm run lint
      - npm run test:ci

  - language: node_js
    node_js:
      - "10"

    cache: npm

    before_install:
      - cd services/frontend
      - npm install -g greenkeeper-lockfile
      
    install:  
      - npm install

    before_script: greenkeeper-lockfile-update
    after_script: greenkeeper-lockfile-upload

    script:
      - npm run build
    