export enum CustomEnv {
	MONGODB_HOST = 'MONGODB_HOST',
	MONGODB_PORT = 'MONGODB_PORT',
	MONGODB_USER = 'MONGODB_USER',
	MONGODB_PASSWORD = 'MONGODB_PASSWORD',
	MONGODB_DATABASE = 'MONGODB_DATABASE',
	MONGODB_CONNECTION_STRING = 'MONGODB_CONNECTION_STRING',

	REST_PORT = 'REST_PORT',

	LOGIN_PASSWORD = 'LOGIN_PASSWORD',

	JWT_SECRET = 'JWT_SECRET'
}