export enum CustomEnv {
    MONGODB_HOST = 'MONGODB_HOST',
    MONGODB_PORT = 'MONGODB_PORT',
    MONGODB_USER = 'MONGODB_USER',
    MONGODB_PASSWORD = 'MONGODB_PASSWORD',
    MONGODB_DATABASE = 'MONGODB_DATABASE',

    REST_PORT = 'REST_PORT'
}