export const SHEETS_FETCHING = 'SHEETS_FETCHING';
export type SHEETS_FETCHING = typeof SHEETS_FETCHING;
export const SHEETS_FETCHED = 'SHEETS_FETCHED';
export type SHEETS_FETCHED = typeof SHEETS_FETCHED;
export const SHEETS_FETCH_FAILED = 'SHEETS_FETCH_FAILED';
export type SHEETS_FETCH_FAILED = typeof SHEETS_FETCH_FAILED;